version: '3.7'
services:
    ielts-gibberish-database:
        image: postgres:14.10
        container_name: ielts-gibberish-postgres
        restart: always
        ports:
            - '5431:5432'
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 512M
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: ielts-gibberish
        volumes:
            - 'ielts-gibberish-postgres-data:/var/lib/postgresql/data'

    ielts-gibberish-test-database:
        image: postgres:14.10
        container_name: ielts-gibberish-test-postgres
        restart: always
        ports:
            - '5429:5432'
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 512M
        environment:
            POSTGRES_PASSWORD: 123
            POSTGRES_USER: postgres
            POSTGRES_DB: ielts-gibberish
        # https://www.postgresql.org/docs/14/runtime-config-wal.html
        command: -c fsync=off -c full_page_writes=off
        volumes:
            - 'ielts-gibberish-test-postgres-data:/var/lib/postgresql/data'

volumes:
    ielts-gibberish-postgres-data:
        name: ielts-gibberish-postgres-data
        driver: local
    ielts-gibberish-test-postgres-data:
        name: ielts-gibberish-test-postgres-data
        driver: local
